Upgrade to k2, add Qodana, remove Kotlin/js
jetbrains-academy/kotlin-onboarding-object-oriented-programming pull request #172
Opened 2024-07-25 02:51 UTC by Daoortor

2024-07-30 19:06 UTC, mikrise2 requested changes
Good job!
Please also fix workflows files as I wrote [here](https://github.com/jetbrains-academy/kotlin-onboarding-object-oriented-programming/pull/172)

2024-07-30 19:06 UTC, mikrise2 commented on build.gradle.kts
> +    val jvmVersionNumber = jvmVersion.toString().takeLastWhile { it.isDigit() }
Please rename it and also just use `jvmVersion.target`

2024-07-30 19:06 UTC, mikrise2 commented on .github/workflows/qodana.yml
> +          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
I think here is some problems with the code formatting

2024-07-31 22:56 UTC, Daoortor commented
Apparently, Qodana build fails now because the QODANA_TOKEN secret is not in the head repository.

2024-08-06 07:23 UTC, nbirillo requested changes
As I can see you have not updated the resources in the servers with updated compiled front end, please do it to double check if everything is working. You need to build the frontend (yarn run build) and then run the `serveResourcesTask` task for the necessary project.

I will come back soon with a token for Qodana

2024-08-06 07:23 UTC, nbirillo commented on wordsGeneratorServer/wordsGeneratorServerFinishGame/src/main/kotlin/jetbrains/kotlin/course/words/generator/results/GameResultsService.kt
> +    fun getAllGameResults(): List<GameResult> = gameHistory.reversed()
What if the student does not explicitly specify the return type? I'd suggest adding a check that will handle this case in the tests, WDYT?

2024-08-16 18:33 UTC, merged